### ISSUE TITLE
Black screen recorded / ios7?

### ISSUE THREAD

**Issue by chadobado** [nicolasgomollon/RecordScreen#4] opened 2014-07-19 21:53 UTC
Assuming this project, like it's parent, is dead and not supporting ios7?

Thanks,

Chad

**Comment by mayank070188** [comment] 2014-10-16 06:07
Hello, Firstly very thanks for your project on Git, I want to use it for internal purpose only, but i am facing a black screen issue on my iPhone. I am using iOS 8/7, xcode 5.1.1. /6 and iPhone 4S/5.. but having the same problem... can you plz just point me the prob or fix it :)Thanks in advanced. Waiting for your Reply.

**Comment by nicolasgomollon** [comment] 2014-10-16 06:18
Duplicate of Issue #3.

Please refer to the following two issues:
https://github.com/coolstar/RecordMyScreen/issues/57
https://github.com/coolstar/RecordMyScreen/issues/60

**Closed as completed by nicolasgomollon** 2014-10-16 06:18 UTC

**Comment by mayank070188** [comment] 2014-10-16 06:39
Hey Thanks Nicolas :) for a very quick response. I dont want to upload this anywhere, i want it for my purpose only... Its sad to know that people illegally using the code :(, You have mentioned the solution for the problem too there but i m noob that i am not able to understand it. Can you please tell me the solution in a lil detail way. or any help you can do for me.. Thanks :)

**Comment by nicolasgomollon** [comment] 2014-10-16 07:07
Look, I’d love to help, but unfortunately, I have no clue how to write the code that does the actual screen recording. I only started this project to play around with some design concepts I had in mind, and used [RecordMyScreen](https://github.com/coolstar/RecordMyScreen) as a starting point. Therefore, you should direct any questions about the recording functionality to [@coolstar](https://github.com/coolstar).

**Comment by mayank070188** [comment] 2014-10-16 07:11
Hey,

Thanks. For the help. i will ask to coolstar. hope he helps me to get some
things done. :)

On Thu, Oct 16, 2014 at 12:37 PM, Nicolas Gomollon <notifications@github.com

> wrote:
> 
> Look, I’d love to help, but unfortunately, I have no clue how to write the
> code that does the actual screen recording. I only started this project to
> play around with some design concepts I had in mind, and used
> RecordMyScreen https://github.com/coolstar/RecordMyScreen as a starting
> point. Therefore, you should direct any questions about the recording
> functionality to @coolstar https://github.com/coolstar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nicolasgomollon/RecordScreen/issues/4#issuecomment-59322259
> .

## 

_Thanks & Regards,_

_Mayank Mathur_
+91 - 9561515591
